export const milestones = [{
    title: "Ochtend op het zadel",
    description: "Tijd voor één ritje van 100km",
    type: 'ride',
    goal: 100,
    badge: '',
  },
  {
    title: "Halve dag op het zadel",
    description: "Tijd voor één ritje van 150km",
    type: 'ride',
    goal: 150,
    badge: '',
  },
  {
    title: "Volle dag op het zadel",
    description: "Tijd voor één ritje van 200km",
    type: 'ride',
    goal: 200,
    badge: '',
  },
  {
    title: "1000km in een maand",
    description: "Rij 1000km in één maand",
    type: 'month',
    goal: 1000,
    badge: '',
  },
  {
    title: "1500km in een maand",
    description: "Rij 1500km in één maand",
    type: 'month',
    goal: 1500,
    badge: '',
  },
  {
    title: "2000km in een maand",
    description: "Rij 2000km in één maand",
    type: 'month',
    goal: 2000,
    badge: '',
  },
  {
    title: "5000km in een jaar",
    description: "Rij 5000km in één jaar",
    type: 'year',
    goal: 5000,
    badge: '',
  },
  {
    title: "10000 in een jaar",
    description: "Rij 10000km in één jaar",
    type: 'year',
    goal: 10000,
    badge: '',
  },
  {
    title: "15000km in een jaar",
    description: "Rij 15000km in één jaar",
    type: 'year',
    goal: 15000,
    badge: '',
  },
  {
    title: "5 uitdagingen",
    description: "Voltooi in totaal 5 uitdagingen",
    type: 'challenges',
    goal: 5,
    badge: '',
  },
  {
    title: "10 uitdagingen",
    description: "Voltooi in totaal 10 uitdagingen",
    type: 'challenges',
    goal: 10,
    badge: '',
  },
  {
    title: "25 uitdagingen",
    description: "Voltooi in totaal 25 uitdagingen",
    type: 'challenges',
    goal: 25,
    badge: '',
  },
  {
    title: "50 uitdagingen",
    description: "Voltooi in totaal 50 uitdagingen",
    type: 'challenges',
    goal: 50,
    badge: '',
  },
  {
    title: "5 doelstellingen",
    description: "Voltooi in totaal 5 doelstellingen",
    type: 'goals',
    goal: 5,
    badge: '',
  },
  {
    title: "10 doelstellingen",
    description: "Voltooi in totaal 10 doelstellingen",
    type: 'goals',
    goal: 10,
    badge: '',
  },
  {
    title: "25 doelstellingen",
    description: "Voltooi in totaal 25 doelstellingen",
    type: 'goals',
    goal: 25,
    badge: '',
  },
  {
    title: "50 doelstellingen",
    description: "Voltooi in totaal 50 doelstellingen",
    type: 'goals',
    goal: 50,
    badge: '',
  },
];